### ISSUE TITLE
/tmp tmpfs is filled very quickly, Errno 28 No space left on device

### ISSUE THREAD

**Issue by jhub95** [DIYBookScanner/spreads#185]
Error: [(u'/media/kitaplar/scans/0760_Elimizdeki_incil_saglamdir/raw/045.jpg', u'/tmp/tmpGLAgnz/data/raw/045.jpg', '[Errno 28] No space left on device')]

I'm not sure what the effects of this error are, but it's probably best to use the tmpfs better.  I'm not convinced that increasing the /tmp file size will solve the problem of running out of space. It seems that Spreads is caching all the raw jpgs in /tmp ?  

spreads@spreadpi /tmp $ df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs          7.2G  710M  6.2G  11% /
/dev/root       7.2G  710M  6.2G  11% /
devtmpfs        214M     0  214M   0% /dev
tmpfs            44M  248K   44M   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            88M     0   88M   0% /run/shm
/dev/mmcblk0p1   64M   15M   50M  23% /boot
tmpfs           100M  100M     0 100% /tmp
tmpfs           100M  128K  100M   1% /var/log
tmpfs           100M  100M     0 100% /tmp
tmpfs            30M     0   30M   0% /var/tmp
tmpfs           100M  128K  100M   1% /var/log
/dev/sda1       1.9T   33G  1.8T   2% /media/kitaplar

**Comment by jbaiter** [comment]
Ouch, that's interesting!

- What version of spreads are you using?
- What are the contents of /tmp and what is its size?

That being said, 100M for tmpfs is really small....

**Comment by jhub95** [comment]
Hey, thanks for responding.

* Version 0.5git20150302.3ede downloaded March 25, 2015 from SpreadPi hub
* Just booting up the Raspberry Pi gives this error. We have around 33GB of book images on the storage drive, so if it's trying to cache them all, good luck! (the drive has lots more space left)
* You say 100M is really small, but it's the default setting from the SpreadPi image. I didn't change it. The contents are something like:
...
spreads@spreadpi ~ $ ls /tmp/
tmpAmXMZD
spreads@spreadpi ~ $ ls /tmp/tmpAmXMZD/
bag-info.txt  bagit.txt  data  manifest-md5.txt  tagmanifest-md5.txt
spreads@spreadpi ~ $ ls /tmp/tmpAmXMZD/data/
book.conf  book.pdf  book.txt  bookhtml  raw

spreads@spreadpi ~ $ du -h --max-depth 1 /tmp/tmpAmXMZD/data
97M	     /tmp/tmpAmXMZD/data/raw
264K	/tmp/tmpAmXMZD/data/bookhtml
100M	/tmp/tmpAmXMZD/data

...
The files and directories listed in data/ are of the same type of files we have in the project folder directory on the attached USB drive.

FYI, setting up SpreadPi is really easy. After flashing the image to the SD card, Spreads was up and running in no time flat (the web interface anyway).  Of course I changed the preferences, and then set the project directory to a USB attached hard drive that stores the RAW jpgs plus a bunch of other post processing files. Other than that I didn't have to change anything. But it won't actually take pictures yet, probably because of this 'no space left on device' error.

**Comment by jbaiter** [comment]
Thanks, that makes things a lot clearer!
So if I understand correctly, the situation is as follows:

- You have changed the project directory in the configuration to point to your external drive
- In that directory there is about 33GB worth of scans that you would like to import into spreads

I think your issue stems from the fact that those workflows on the storage drive were either done with an older version of spreads (since before I changed the workflow structore to follow BagIt conventions) or without spreads at all.
The files from your directory hint at the latter possibility, since the PDF procuded by spreads would usually be located under `data/out/book.pdf`.
The error now occurs because when spreads first scans the project directory for pre-existing workflows, it will try to convert any non-bagit compliant directories (from an older spreads version) to the new structure. For this, it creates a temporary directory where the BagIt structure is created with the 'old' files, and is then copies over to the project directory, replacing the older directory.
Now this is a problem on SpreadPi, because we have only 100MB in `/tmp` (which is usually plenty for regular operation). But in your case, a single one of your pre-BagIt workflow is likely to be bigger than that, hence the error during the conversion.
As a solution to the problem:

- Make sure that the workflow directory contents in the project directory adhere to the following structure:
```
raw/XXX.jpg # Unprocessed images
done/XXX.tif  # Images processed by ScanTailor
out/book.pdf, book.html  # Generated output files
```

Then install and launch the spreads web instance on another machine with plenty of space in `/tmp` with the storage drive configured as the project directory and it should convert all of your workflows to the new format (which will likely take some time, currently there's no indicator in the UI of what is going on). Then you can quit spreads and attach the drive to your SpreadPi box and spreads should start without the error, since there will be no more conversion to do.

**Comment by jhub95** [comment]
Thanks for the help.  The current files are images captured with SpreadPi from last year, circa April 2014.  We're not using ScanTailor. We have customized scripts and Tesseract doing the heavy OCR work. All of the non-Spreads files are from those scripts.

There's no need for us to see all our books in the Spreads UI. Once we have captured good pics of a book it no longer needs to show up in the list.  Since we're a library this means thousands of books possibly.  Plus there is no need to do this conversion every year when we want to update SpreadPi.  We'd rather just have Spreads ignore the older content rather than try to convert it. 

I may just create a new projects folder and start from scratch.  I hope this type of issue doesn't happen too often as I'd like to keep our directory structure consistent for our other scripts. 

Will adding non-Spreads files be a problem for BagIt? Currently each book directory has a structure like this:

2039_Book_Title
 -> book.conf
 -> book.pdf
 -> book.txt
 -> bookhtml -> (directory with outputted html)
 -> raw -> (directory with camera jpgs)

**Comment by jbaiter** [comment]
> There's no need for us to see all our books in the Spreads UI. Once we have captured good pics of a book it no longer needs to show up in the list. Since we're a library this means thousands of books possibly.

Had not thought of that, thanks for mentioning your use case. Most of the people I talked to were using Spreads in smaller environments (i.e. a few dozen books), glad to see someone using it for something bigger. Have you thought of moving "finished" books to another directory? I'm a bit wary of removing the list in the web-interface, to be honest, since I find it to pretty useful. I will, however, add pagination at some point, so that only a few workflows are shown at once
.
> Plus there is no need to do this conversion every year when we want to update SpreadPi. We'd rather just have Spreads ignore the older content rather than try to convert it. 
That was almost certainly a one-time thing and is to be expected with 0.x releases. I try to keep changes like that to a minimum and if I do them to make them as unobtrusive to users as possible (hence the automatic conversion), however in your case that definitely did more harm than good, sorry for that.

> Will adding non-Spreads files be a problem for BagIt?

Not at all, BagIt does not care about the contents of a bag. You just won't be able to display your post-processed or output files in the interface, but as far as I understood it you're not interested in that anyways.

That being said, I'd be really glad to hear some more about the ways you're using spreads at your library and where you think things would need improvement to facilitate usage in such larger scenarios. Send me an email when you feel like sharing :-)

**Comment by jbaiter** [comment]
As for the issue at hand, I just added a new advanced configuration option `convert_old` that can be disabled to skip conversion of old-style workflows:
https://github.com/DIYBookScanner/spreads/commit/a008d41f03220f119f546a744054960888dffade
Does that work for you?

**Comment by jhub95** [comment]
jbaiter, I'd like to try out the new configuration option and see what happens. I downloaded Version 0.5git20150327.4ab5 and it wasn't included.  Should I be using git to integrate your commits?  If so please inform me from which directory and which git command I should run. Thanks.

BTW, SpreadPi is working much nicer now than it was this time last year! It was so easy to set up and it's so easy to use!

So the way I understand our situation is this: using our current directory structure is not a problem for Spreads or BagIt, but converting a large set of older projects to the new is a problem.  So by disabling the conversion process we can keep our old directory, and as we create new projects they will be stored in the BagIt way (which is not a problem for our other scripts).  This sound accurate?

**Comment by jbaiter** [comment]
@jhub95, `convert_old` is an advanced option, so you have to tick the "Show advanced options" check box to be able to see it.

**Comment by jhub95** [comment]
I have clicked advanced, and I don't see it under core. Also checking
config.yaml I don't see it under core. Can you confirm that it was merged?
The SpreadPi version I'm using was downloaded Monday.

**Comment by jhub95** [comment]
@jbaiter, Hi I still don't see the option (even with Advanced ticked) for the convert_old. The latest img I have is from March 27.

**Comment by jbaiter** [comment]
@jhub95, can you try the March 28 bundle? I just did a clean install with it and the option is there, under "Preferences": http://i.imgur.com/RZrROaT.png

**Comment by jhub95** [comment]
Which link should I download from? I've been downloading from
http://buildbot.diybookscanner.org/nightly/spreadpi-latest.img.7z from the
page https://github.com/DIYBookScanner/spreadpi

Seeing how I just downloaded from there today (April 14) and got the March
27th version it makes me think I may not be downloading from the correct
location.

**Comment by jbaiter** [comment]
There we have it.... The issue is that on the day I added the commit, the Chinese DDoS on GitHub started... Since the script that builds the spreadpi image fetches data from GitHub, it failed on that day, hence no image for the 28th.
You can see it in the log here: http://buildbot.diybookscanner.org/buildbot/builders/nightly-spreadpi/builds/49/steps/Build%20image/logs/buildlog

An easy solution would be to ssh onto the box and run the following as root:

    # pip install http://buildbot.diybookscanner.org/nightly/spreads-latest.tar.gz

That should install the latest version without you having to download and flash a new image.
I've just triggered a new build, the new image should be up in a few hours.
Sorry for the hassle, I really should configure an email alert for when builds fail :/

**Comment by jhub95** [comment]
Hi Johannes,

So I've tried the fix you created by unchecking the 'convert old workflows' advanced option and I still get issues. I created another folder on my Usb drive and was able to acquire images to it just fine, so I'm certain there's nothing wrong with my USB mount setup.  Here's the error log:

    2015-04-22 10:51:28,756 Specified workflow directory is not structured according to BagIt convertions and automatic conversion has been disabled (check `convert_old` setting) [spreadsplug.web] [ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/spreadsplug/web/endpoints.py", line 522, in list_workflows
    workflows = Workflow.find_all(app.config['base_path'])
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 355, in find_all
    workflow = cls(candidate)
  File "/usr/local/lib/python2.7/dist-packages/spreads/workflow.py", line 442, in __init__
    "Specified workflow directory is not structured according "
BagError: Specified workflow directory is not structured according to BagIt convertions and automatic conversion has been disabled (check `convert_old` setting)
2015-04-22 10:51:28,809 500 GET /api/workflow (10.0.0.76) 601.37ms [tornado.access] [ERROR]


As a reminder the desired target directory sitting on the usb drive is scans/ which contains many directories.

**Comment by jbaiter** [comment]
Justin, sorry for that, that exception should of course have been caught higher up, seems I didn't think that far when coding...
Fixed now, so you can either wait for the new nightly package or just grab the latest `workflow.py` from GitHub and copy it over the old one.

https://github.com/DIYBookScanner/spreads/commit/cbc02d41dfbc8e2f65905e4f9e67820caf85a3cc
